name: Prettier

on:
  workflow_dispatch: # On manual trigger
  schedule:
    - cron: "0 0 * * 0" # Every day at midnight

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install app dependencies
        run: |
          pnpm install
          pnpm add -D prettier-plugin-tailwindcss @ianvs/prettier-plugin-sort-imports

      - name: Prettier
        run: pnpm prettier

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: unsafe format
          title: Run unsafe Prettier
          branch: unsafe-prettier
